# Generated by Django 4.2.16 on 2024-11-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=50)),
                ('deal_base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_fetched', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
