# Generated by Django 4.2.16 on 2024-11-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='profiles/0.png', upload_to='profiles/'),
        ),
    ]
